import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/utils/chakra-provider";
import { fonts } from "@/utils/chakra-font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.rubik.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
