import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/utils/chakra-provider";
import { fonts } from "@/utils/chakra-font";
import { Container } from "@chakra-ui/react";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.rubik.variable}>
        <Providers>
          <Navbar />
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
