import type { Metadata } from "next";
import "./globals.css";
import { fonts } from "@/utils/chakra-font";
import { Box, Container, Flex } from "@chakra-ui/react";
import Navbar from "@/components/navbar";
import { AppChakraProvider } from "@/utils/app-chakra-provider";
import { Providers } from "@/utils/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.rubik.variable}>
        <AppChakraProvider>
          <Providers>
            <Flex as="header" position="fixed" w="100%" bg="white">
              <Box shadow="sm" w="100%">
                <Navbar />
              </Box>
            </Flex>
            <Flex>
              <Container as="main" mt={16}>
                {children}
              </Container>
            </Flex>
          </Providers>
        </AppChakraProvider>
      </body>
    </html>
  );
}
